#!/bin/bash
# Reef Masternode update Script V1.3 for Ubuntu 16.04 LTS
# (c) 2018 by Dwigt007 for Reef Coin


#Color codes
RED='\033[0;91m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

#REEF TCP port
PORT=9857
RPC=9859

#Clear keyboard input buffer
function clear_stdin { while read -r -t 0; do read -r; done; }

#Delay script execution for N seconds
function delay { echo -e "${GREEN}Sleep for $1 seconds...${NC}"; sleep "$1"; }

#Stop daemon if it's already running
function stop_daemon {
    if pgrep -x 'reefd' > /dev/null; then
        echo -e "${YELLOW}Attempting to stop reefd${NC}"
        reef-cli stop
        delay 30
        if pgrep -x 'reef' > /dev/null; then
            echo -e "${RED}reefd daemon is still running!${NC} \a"
            echo -e "${RED}Attempting to kill...${NC}"
            pkill reefd
            delay 30
            if pgrep -x 'reefd' > /dev/null; then
                echo -e "${RED}Can't stop reefd! Reboot and try again...${NC} \a"
                exit 2
            fi
        fi
    fi
}

#Process command line parameters
genkey=$1

clear

echo -e "${YELLOW}Reef Masternode Setup Script V1.3 for Ubuntu 16.04 LTS${NC}"
echo -e "${GREEN}Updating system and installing required packages...${NC}"
sudo DEBIAN_FRONTEND=noninteractive apt-get update -y


#KILL THE MFER
pkill ./reefd
killall reefd
pklil reefd
sleep 30
rm -r ~/ReefMasternodeSetup/v1.2ubuntu16
rm -r .reefcore 
rm -rf /usr/bin/reef*
 
#Installing Daemon
 cd ~
wget https://transfer.sh/17SR9/fork_1.3.tar.gz
tar -xzf fork_1.3.tar.gz -C ~/ReefMasternodeSetup
rm -rf fork_1.3.tar.gz

  stop_daemon
 
 # Deploy binaries to /usr/bin
 sudo cp ~/ReefMasternodeSetup/fork_1.3/reef* /usr/bin/
 sudo chmod 755 -R ~/ReefMasternodeSetup
 sudo chmod 755 /usr/bin/reef*
 

    #Starting daemon first time just to generate masternode private key
    reefd -daemon
    delay 30

echo -e "========================================================================
${YELLOW}Masternode update setup is complete!${NC}
========================================================================
Masternode was installed with VPS IP Address: ${YELLOW}$publicip${NC}
Masternode Private Key: ${YELLOW}$genkey${NC}
Now you can add the following string to the masternode.conf file
for your Hot Wallet (the wallet with your REEFCOIN collateral funds):
======================================================================== \a"
echo -e "${YELLOW}mn1 $publicip:$PORT $genkey TxId TxIdx${NC}"
echo -e "========================================================================

read -p "*** Press any key to continue ***" -n1 -s

echo -e "1) Wait for the node wallet on this VPS to sync with the other nodes
on the network. Eventually the 'Is Synced' status will change
to 'true', which will indicate a comlete sync, although it may take
from several minutes to several hours depending on the network state.
Your initial Masternode Status may read:
    ${YELLOW}Node just started, not yet activated${NC} or
    ${YELLOW}Node  is not in masternode list${NC}, which is normal and expected.
2) Wait at least until 'IsBlockchainSynced' status becomes 'true'.
At this point you can go to your wallet and issue a start
command by either using Debug Console:
    Tools->Debug Console-> enter: ${YELLOW}masternode start-alias mn1${NC}
    where ${YELLOW}mn1${NC} is the name of your masternode (alias)
    as it was entered in the masternode.conf file
    
or by using wallet GUI:
    Masternodes -> Select masternode -> RightClick -> ${YELLOW}start alias${NC}
Once completed step (2), return to this VPS console and wait for the
Masternode Status to change to: 'Masternode successfully started'.
This will indicate that your masternode is fully functional and
you can celebrate this achievement!
Currently your masternode is syncing with the REEF network...
The following screen will display in real-time
the list of peer connections, the status of your masternode,
node synchronization status and additional network and node stats.
"
clear_stdin
read -p "*** Press any key to continue ***" -n1 -s

echo -e "
${GREEN}...scroll up to see previous screens...${NC}
Here are some useful commands and tools for masternode troubleshooting:
========================================================================
To view masternode configuration produced by this script in reef.conf:
${YELLOW}cat ~/.reefcore/reef.conf${NC}
Here is your reef.conf generated by this script:
-------------------------------------------------${YELLOW}"
cat ~/.reefcore/reef.conf
echo -e "${NC}-------------------------------------------------
NOTE: To edit reef.conf, first stop the reefd daemon,
then edit the reef.conf file and save it in nano: (Ctrl-X + Y + Enter),
then start the reefd daemon back up:
             to stop:   ${YELLOW}reef-cli stop${NC}
             to edit:   ${YELLOW}nano ~/.reefcore/reef.conf${NC}
             to start:  ${YELLOW}reefd${NC}
========================================================================
To view Itis debug log showing all MN network activity in realtime:
             ${YELLOW}tail -f ~/.reefcore/debug.log${NC}
========================================================================
To monitor system resource utilization and running processes:
                   ${YELLOW}htop${NC}
========================================================================
To view the list of peer connections, status of your masternode, 
sync status etc. in real-time, run the nodemon.sh script:
                 ${YELLOW}nodemon.sh${NC}
or just type 'node' and hit <TAB> to autocomplete script name.
========================================================================
Enjoy your REEF Masternode and thanks for using this setup script!

If you found this script useful, please donate to : 
${GREEN}RLrk3XGs7ZYdDSE2Emqhg8hPWvGVcRpjNB${NC}
...and make sure to check back for updates!
Author: Dwigt007
"
delay 30
# Run nodemon.sh
nodemon.sh

# EOF
